### ISSUE TITLE
Some problem in running build.xml

### ISSUE THREAD

**Issue by NingSong1024** [webis-de/ACL-18#2]
Excuse me, could you solve my problem?
    When I run build.xml by ant, it shows that "package javax.xml.bind is not visible". What is wrong with this ? 
    Thank you very much!

**Comment by johanneskiesel** [comment]
Hi Ning,

This is most likely a problem with Java 9. Can you try to use "--add-modules java.xml.bind"?

https://stackoverflow.com/a/46651783

**Comment by johanneskiesel** [comment]
Close this issue after nearly two months of no reply
