### ISSUE TITLE
Partial source code is not available?

### ISSUE THREAD

**Issue by WeiyueSu** [webis-de/ACL-18#3]
Hi johanneskiesel,
I just read the code and can't find the code under the "de.aitools.ie.uima" dir. But .class file is found in the aitools4-ie-uima.jar. Is these source code publicly available?

**Comment by johanneskiesel** [comment]
Hi Weiyue,

We do not have a public repository for that code, but I added the source code (should be the same version I used to built the jar) to the release:

  https://github.com/webis-de/ACL-18/releases

Unfortunately, I currently can not provide support for that code.

Good luck! ;)
